# `map` de nuevo

`map` evalúa una función sobre *cada elemento* de un arreglo:

In [21]:
?map

Base.map(f, c...) -> collection

   Transform collection "c" by applying "f" to each element. For
   multiple collection arguments, apply "f" elementwise.

      julia> map((x) -> x * 2, [1, 2, 3])
      3-element Array{Int64,1}:
       2
       4
       6

      julia> map(+, [1, 2, 3], [10, 20, 30])
      3-element Array{Int64,1}:
       11
       22
       33


In [22]:
f(x) = x^2
xx = collect(1:10)

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [23]:
map(f, xx)

10-element Array{Int64,1}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

In [26]:
y = map(x -> x^3, xx)

10-element Array{Int64,1}:
    1
    8
   27
   64
  125
  216
  343
  512
  729
 1000

In [25]:
xx

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

# Un poquito de interacción con la terminal

Voy a usar `;` que manda comandos al shell / terminal. También se puede usar una terminal directamente.

In [1]:
;ls

Clase 08-17.ipynb
Clase 08-19.ipynb
Clase 08-31.ipynb
Clase 09-07.ipynb
Clase 09-09.ipynb
Clase 09-14.ipynb
Clase 24-08.ipynb
Clase 26-08.ipynb


In [2]:
pwd

pwd (generic function with 1 method)

In [3]:
?pwd

INFO: Loading help data...


Base.pwd() -> String

   Get the current working directory.


In [5]:
pwd()

"/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases"

In [6]:
typeof(ans)

ASCIIString (constructor with 2 methods)

In [7]:
ls()

LoadError: ls not defined
while loading In[7], in expression starting on line 1

In [9]:
;pwd

/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases


Si quisiéramos que devolviera la respuesta en una variable:

In [11]:
comando = `pwd`

`pwd`

In [12]:
typeof(ans)

Cmd (constructor with 1 method)

In [13]:
run(comando)

/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases


In [15]:
a = run(comando)

/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases


In [19]:
a = readall(comando)  # corre el comando *y* devuelve la salida del comando

"/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases\n"

In [20]:
a

"/Users/dpsanders/Dropbox/docencia/fisica_computacional/2016-1/clases\n"

In [27]:
;ls

Clase 08-17.ipynb
Clase 08-19.ipynb
Clase 08-31.ipynb
Clase 09-07.ipynb
Clase 09-09.ipynb
Clase 09-14.ipynb
Clase 24-08.ipynb
Clase 26-08.ipynb


In [28]:
mes = 8

8

Cómo puedo encontrar con `ls` sólo los notebooks de este mes

In [29]:
;ls *08* 

Clase 08-17.ipynb
Clase 08-19.ipynb
Clase 08-31.ipynb
Clase 24-08.ipynb
Clase 26-08.ipynb


# Un poco de `git` 

In [37]:
;git log

commit 0937a0ea21ec2d2ab019f7628e64b2d0067c582e
Author: David Sanders <dpsanders@gmail.com>
Date:   Mon Sep 14 12:25:24 2015 -0500

    Agregué notebook 11, integración numérica

commit bb2d6b4015e98ee26c20b991832d8c25ecb9fee8
Author: David Sanders <dpsanders@gmail.com>
Date:   Wed Sep 9 15:38:35 2015 -0500

    Quité acentos de nombre de notebook 10

commit 40c8b5b1885e02ea61acc24c072be6af65a96a09
Author: Rodrigo Leal Cervantes <rodrigolealc@ciencias.unam.mx>
Date:   Wed Sep 9 15:25:01 2015 -0500

    Corregí errores de dedo

commit fa713dac8848a1efa01afd37d93ed126294233d4
Author: David Sanders <dpsanders@gmail.com>
Date:   Wed Sep 9 15:06:07 2015 -0500

    Modificaciones a notebook 10

commit 76b6013c5474469ca149336bdbb3619a386d19d8
Author: David Sanders <dpsanders@gmail.com>
Date:   Wed Sep 9 13:19:34 2015 -0500

    Agregué notebook 10, diferenciación numérica

commit 24703044ecec646cc6f026463c718a440be6fe2b
Author: David Sanders <dpsanders@gmail.com>
Date:   Wed Sep 9 12:43:22 20

In [38]:
;git diff bb2d6b401 40c8b5b1

diff --git a/notas/10. Diferenciacion numerica.ipynb b/notas/10. Diferenciacion numerica.ipynb
deleted file mode 100644
index bad4b54..0000000
--- a/notas/10. Diferenciacion numerica.ipynb	
+++ /dev/null
@@ -1,119 +0,0 @@
-{
- "cells": [
-  {
-   "cell_type": "markdown",
-   "metadata": {},
-   "source": [
-    "# Diferenciación numérica"
-   ]
-  },
-  {
-   "cell_type": "markdown",
-   "metadata": {},
-   "source": [
-    "Como ya hemos visto con el método de Newton, a menudo es necesario calcular la derivada de una función. Próximamente también querremos aproximar la derivada de una función definida solamente en ciertos puntos, e.g. de una malla.\n",
-    "\n",
-    "Por lo tanto, un tema fundamental en la física computacional es el calcular derivadas numéricamente. En este notebook, veremos una manera clásica de calcular derivadas con diferencias finitas. Sin embargo, ¡**el hecho de ser clásico no necesariamente implica que sea la manera recomendada de hacerlo**! Posteriormente ver

In [39]:
?linrange

Base.linrange(start, end, length)

   Construct a range by length, given a starting and ending value.


In [42]:
linrange(1, 10, 21)

1.0:0.45:10.0